version: 2
updates:
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "GarthDB"
    assignees:
      - "GarthDB"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"

  # npm dependencies (for Changesets)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "GarthDB"
    assignees:
      - "GarthDB"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "GarthDB"
    assignees:
      - "GarthDB"
    commit-message:
      prefix: "ci"
