[hooks]
pre-commit = "cargo fmt --all && cargo clippy --all-targets --all-features -- -D warnings -A clippy::too_many_lines -A clippy::missing_docs_in_private_items -A clippy::missing_errors_doc -A clippy::missing_panics_doc -A clippy::must_use_candidate"
pre-push = "cargo test --all-features"

[logging]
verbose = true
