name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      - name: Run Tests
        run: cargo test --verbose

      - name: Check Formatting
        if: matrix.os == 'ubuntu-latest'
        run: cargo fmt -- --check

      - name: Clippy
        if: matrix.os == 'ubuntu-latest'
        run: cargo clippy -- -D warnings
