name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    outputs:
      published: ${{ steps.changesets.outputs.published }}
      publishedPackages: ${{ steps.changesets.outputs.publishedPackages }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Version packages with Changesets
        id: changesets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if npm run release; then
            echo "published=true" >> $GITHUB_OUTPUT
          else
            echo "published=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and push version changes
        if: steps.changesets.outputs.published == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Version packages" || exit 0
          git push

  build-binaries:
    name: Build Release Binaries
    needs: release
    if: needs.release.outputs.published == 'true'
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: scripture-links-x86_64-unknown-linux-gnu.tar.gz
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            name: scripture-links-x86_64-unknown-linux-musl.tar.gz
          - target: x86_64-apple-darwin
            os: macos-latest
            name: scripture-links-x86_64-apple-darwin.tar.gz
          - target: aarch64-apple-darwin
            os: macos-latest
            name: scripture-links-aarch64-apple-darwin.tar.gz
          - target: x86_64-pc-windows-msvc
            os: windows-2022
            name: scripture-links-x86_64-pc-windows-msvc.zip
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Build Binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package Binary (Unix)
        if: matrix.os != 'windows-2022'
        run: |
          cd target/${{ matrix.target }}/release
          tar -czf ../../../${{ matrix.name }} scripture-links
          cd -

      - name: Package Binary (Windows)
        if: matrix.os == 'windows-2022'
        run: |
          cd target/${{ matrix.target }}/release
          7z a ../../../${{ matrix.name }} scripture-links.exe
          cd -

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}

  create-release:
    name: Create GitHub Release
    needs: [release, build-binaries]
    if: needs.release.outputs.published == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Extract Version
        id: extract_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=v$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          name: Release ${{ steps.extract_version.outputs.version }}
          draft: false
          prerelease: false
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-homebrew:
    name: Update Homebrew Formula
    needs: [release, create-release]
    if: needs.release.outputs.published == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v5

      - name: Checkout Homebrew Tap
        uses: actions/checkout@v5
        with:
          repository: GarthDB/homebrew-scripture-links
          token: ${{ secrets.HOMEBREW_PAT }}
          path: homebrew-tap

      - name: Extract Version
        id: extract_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Download Release Assets and Calculate Checksums
        run: |
          VERSION="${{ steps.extract_version.outputs.version }}"
          
          # Download macOS binaries
          curl -L -o scripture-links-aarch64-apple-darwin.tar.gz \
            "https://github.com/GarthDB/scripture-links/releases/download/v${VERSION}/scripture-links-aarch64-apple-darwin.tar.gz"
          curl -L -o scripture-links-x86_64-apple-darwin.tar.gz \
            "https://github.com/GarthDB/scripture-links/releases/download/v${VERSION}/scripture-links-x86_64-apple-darwin.tar.gz"
          curl -L -o scripture-links-x86_64-unknown-linux-gnu.tar.gz \
            "https://github.com/GarthDB/scripture-links/releases/download/v${VERSION}/scripture-links-x86_64-unknown-linux-gnu.tar.gz"
          
          # Calculate checksums
          MACOS_ARM64_SHA=$(shasum -a 256 scripture-links-aarch64-apple-darwin.tar.gz | cut -d' ' -f1)
          MACOS_X64_SHA=$(shasum -a 256 scripture-links-x86_64-apple-darwin.tar.gz | cut -d' ' -f1)
          LINUX_X64_SHA=$(shasum -a 256 scripture-links-x86_64-unknown-linux-gnu.tar.gz | cut -d' ' -f1)
          
          echo "MACOS_ARM64_SHA=$MACOS_ARM64_SHA" >> $GITHUB_ENV
          echo "MACOS_X64_SHA=$MACOS_X64_SHA" >> $GITHUB_ENV
          echo "LINUX_X64_SHA=$LINUX_X64_SHA" >> $GITHUB_ENV

      - name: Update Homebrew Formula
        run: |
          VERSION="${{ steps.extract_version.outputs.version }}"
          
          # Update the formula file
          cat > homebrew-tap/Formula/scripture-links.rb << EOF
          class ScriptureLinks < Formula
            desc "Convert scripture references to URLs for ChurchofJesusChrist.org"
            homepage "https://github.com/GarthDB/scripture-links"
            version "${VERSION}"
            license "MIT"
          
            on_macos do
              if Hardware::CPU.arm?
                url "https://github.com/GarthDB/scripture-links/releases/download/v${VERSION}/scripture-links-aarch64-apple-darwin.tar.gz"
                sha256 "${MACOS_ARM64_SHA}"
              else
                url "https://github.com/GarthDB/scripture-links/releases/download/v${VERSION}/scripture-links-x86_64-apple-darwin.tar.gz"
                sha256 "${MACOS_X64_SHA}"
              end
            end
          
            on_linux do
              url "https://github.com/GarthDB/scripture-links/releases/download/v${VERSION}/scripture-links-x86_64-unknown-linux-gnu.tar.gz"
              sha256 "${LINUX_X64_SHA}"
            end
          
            def install
              bin.install "scripture-links"
            end
          
            test do
              # Test basic functionality
              output = shell_output("#{bin}/scripture-links --reference 'Genesis 1:1'")
              assert_match "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/1", output
              
              # Test help command
              help_output = shell_output("#{bin}/scripture-links --help")
              assert_match "Generate links to scriptures on ChurchofJesusChrist.org", help_output
            end
          end
          EOF

      - name: Commit and Push Formula Update
        run: |
          cd homebrew-tap
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Formula/scripture-links.rb
          git commit -m "Update scripture-links to v${{ steps.extract_version.outputs.version }}"
          git push
